; PlatformIO Project Configuration File v1.5
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:development]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_8mb_ota.csv
board_build.filesystem = littlefs
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DESP32_S3_DEVKITC1
	-DCOPROC_ESP32C3_BEETLE
	-DGATEWAY_BUILTIN_SENSOR_TYPE=GATEWAY_BUILTIN_SENSOR_BMP280
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson @ ^7.0.0
	adafruit/Adafruit NeoPixel @ ^1.12.3
	knolleary/PubSubClient @ ^2.8
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BMP280 Library @ ^2.6.8
	adafruit/Adafruit BME280 Library @ ^2.3.0
upload_port = COM13
monitor_port = COM13

[env:gateway_v1a]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_8mb_ota.csv
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DXIAO_ESP32_S3
    -DCOPROC_ESP32C3_SUPER_MINI
	-DGATEWAY_BUILTIN_SENSOR_TYPE=GATEWAY_BUILTIN_SENSOR_BME280
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit NeoPixel @ ^1.12.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit BME280 Library @ ^2.3.0
upload_port = COM13
monitor_port = COM13

[env:gateway_v1b]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_8mb_ota.csv
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DXIAO_ESP32_S3
    -DCOPROC_ESP32C3_XIAO
	-DGATEWAY_BUILTIN_SENSOR_TYPE=GATEWAY_BUILTIN_SENSOR_BME280
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit NeoPixel @ ^1.12.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit BME280 Library @ ^2.3.0
upload_port = COM13
monitor_port = COM13

[env:gateway_v1c]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_8mb_ota.csv
board_build.filesystem = littlefs
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DXIAO_ESP32_S3
	-DCOPROC_ESP32C3_BEETLE
	-DGATEWAY_BUILTIN_SENSOR_TYPE=GATEWAY_BUILTIN_SENSOR_BME280
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson @ ^7.0.0
	adafruit/Adafruit NeoPixel @ ^1.12.3
	knolleary/PubSubClient @ ^2.8
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BMP280 Library @ ^2.6.8
	adafruit/Adafruit BME280 Library @ ^2.3.0
upload_port = COM13
monitor_port = COM13

[env:gateway_v1d]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_8mb_ota.csv
board_build.filesystem = littlefs
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DESP32_S3_DEVKITC1
    -DCOPROC_ESP32C3_SUPER_MINI
	-DGATEWAY_BUILTIN_SENSOR_TYPE=GATEWAY_BUILTIN_SENSOR_BMP280
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson @ ^7.0.0
	adafruit/Adafruit NeoPixel @ ^1.12.3
	knolleary/PubSubClient @ ^2.8
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BMP280 Library @ ^2.6.8
	adafruit/Adafruit BME280 Library @ ^2.3.0
upload_port = COM13
monitor_port = COM13